import type { AppState } from "./types";

const today = new Date().toISOString().slice(0, 10);
const daysAgo = (days: number) =>
  new Date(Date.now() - days * 86400000).toISOString();

export const seedState: AppState = {
  version: 1,
  timezone: "Asia/Shanghai",
  role: "child",
  activeChildId: "mia",
  children: [
    {
      id: "mia",
      name: "米娅",
      avatar: "🌻",
      color: "#ffb547",
      level: 4,
      experience: 72,
      pointsBalance: 185,
      streakDays: 6,
    },
  ],
  tasks: [
    {
      id: "t1",
      childId: "mia",
      title: "整理自己的书桌",
      description: "把书本分类放回书架，擦干净桌面。",
      category: "生活自理",
      points: 20,
      repeatRule: "daily",
      dueDate: today,
      status: "todo",
      createdAt: daysAgo(4),
    },
    {
      id: "t2",
      childId: "mia",
      title: "阅读 20 分钟",
      description: "选择一本喜欢的书，安静阅读 20 分钟。",
      category: "学习成长",
      points: 30,
      repeatRule: "daily",
      dueDate: today,
      status: "pending_review",
      createdAt: daysAgo(3),
    },
    {
      id: "t3",
      childId: "mia",
      title: "给植物浇水",
      description: "观察植物的土壤，适量浇水并收好水壶。",
      category: "家庭责任",
      points: 15,
      repeatRule: "daily",
      dueDate: today,
      status: "completed",
      createdAt: daysAgo(6),
    },
    {
      id: "t4",
      childId: "mia",
      title: "帮忙摆放餐具",
      description: "晚餐前帮家人准备好餐具。",
      category: "家庭责任",
      points: 15,
      repeatRule: "once",
      dueDate: today,
      status: "completed",
      createdAt: daysAgo(8),
    },
  ],
  submissions: [
    {
      id: "s1",
      taskId: "t2",
      childId: "mia",
      note: "我读完了《小王子》第三章！",
      attachments: [
        { name: "小王子阅读记录.jpg", type: "image" },
        { name: "阅读分享.mp4", type: "video" },
      ],
      submittedAt: daysAgo(0.1),
    },
  ],
  wishes: [
    {
      id: "w1",
      title: "周末看一部电影",
      description: "和家人一起选一部喜欢的电影。",
      pointsCost: 120,
      icon: "🎬",
      color: "#ffcf70",
      isActive: true,
    },
    {
      id: "w2",
      title: "选择一次晚餐",
      description: "今晚的菜单由你来决定。",
      pointsCost: 80,
      icon: "🍕",
      color: "#ff9980",
      isActive: true,
    },
    {
      id: "w3",
      title: "公园探险半日游",
      description: "安排一次特别的户外探险。",
      pointsCost: 260,
      icon: "🗺️",
      color: "#9bd8c8",
      isActive: true,
    },
    {
      id: "w4",
      title: "睡前故事加长版",
      description: "今晚拥有两本睡前故事。",
      pointsCost: 60,
      icon: "📚",
      color: "#bdb2ed",
      isActive: true,
    },
  ],
  ledger: [
    {
      id: "l1",
      childId: "mia",
      amount: 20,
      type: "earned",
      referenceType: "task",
      referenceId: "t4",
      description: "完成「帮忙摆放餐具」",
      createdAt: daysAgo(1),
    },
    {
      id: "l2",
      childId: "mia",
      amount: 15,
      type: "earned",
      referenceType: "task",
      referenceId: "t3",
      description: "完成「给植物浇水」",
      createdAt: daysAgo(2),
    },
    {
      id: "l3",
      childId: "mia",
      amount: -60,
      type: "spent",
      referenceType: "redemption",
      referenceId: "w4",
      description: "兑换「睡前故事加长版」",
      createdAt: daysAgo(3),
    },
  ],
  redemptions: [
    {
      id: "r1",
      wishId: "w4",
      wishTitle: "睡前故事加长版",
      wishIcon: "📚",
      wishColor: "#bdb2ed",
      childId: "mia",
      pointsCost: 60,
      attachments: [],
      createdAt: daysAgo(3),
    },
  ],
};
